#!/bin/bash

### lolcommits hook (begin) ###
export LANG=""
export PATH="/usr/local/bin:$HOME/local/bin:$HOME/.rvm/bin:/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export LOLCOMMITS_DIR="/Users/lejoe/Google Drive/Backups/Lolcommits"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as 

lolcommits --capture --fork --stealth

###  lolcommits hook (end)  ###


### Rescuetime hook (begin) ###
#
# An example hook script to log commit messages
# as a 'daily highlight' in RescueTime Premium
#
# See README.md for more information
#
# To enable this hook:
#
# 1. Place this file in .git/hooks and rename to "post-commit".
#
# 2. Update the value of API_KEY below with a valid RescueTime API key.
#    [ you can generate a key at https://www.rescuetime.com/anapi/manage ]

# Only if there is an file to set the rescuetime api key
if test -f "$HOME/.auth/rescuetime/.rescuetime"; then 
  # Loads rescuetime API Key
  source "$HOME/.auth/rescuetime/.rescuetime"

  # Run only if we set an api key
  if [ ! -z "${RESCUTIME_API_KEY}" ]; then

    API_KEY="$RESCUTIME_API_KEY"

    # REQUIRED FIELDS - Today's date and commit message

    MESSAGE=$(git log -1 HEAD --pretty=format:%s)
    DATE_TODAY=$(date +"%Y-%m-%d")

    # You can edit the LABEL value if you would rather
    # describe these commits differently.

    LABEL='Code Commit'

    # See more filtering examples in README.md

    curl --data "key=$API_KEY&highlight_date=$DATE_TODAY&description=$MESSAGE&source=$LABEL" https://www.rescuetime.com/anapi/highlights_post -s > /dev/null

  fi

  ### Rescuetime hook (end)  ###
fi